name: Argo CD Action
author: Clowd Haus, LLC / Lucas Freitas
description: GitHub action for installing/executing ArgoCD CLI
branding:
  icon: anchor
  color: gray-dark

inputs:
  commands:
    description: >
      Command passed to the CLI
      Reference - https://argoproj.github.io/argo-cd/user-guide/commands/argocd/
    required: true
  version:
    description: >
      Version of Argo CD to install - https://github.com/argoproj/argo-cd/releases
    required: false
    default: 2.3.3

runs:
  using: node16
  main: dist/index.js
